// <auto-generated />
using System;
using ComicBooksAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicBooksAPI.Migrations
{
    [DbContext(typeof(ComicsContext))]
    [Migration("20190119150612_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("ComicBooksAPI.Comics.Comic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cover");

                    b.Property<int?>("Issue");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Release");

                    b.Property<int>("Size");

                    b.Property<Guid?>("TitleId");

                    b.Property<string>("Writer");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("ComicBooksAPI.Titles.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("ComicBooksAPI.Comics.Comic", b =>
                {
                    b.HasOne("ComicBooksAPI.Titles.Title", "Title")
                        .WithMany("Issues")
                        .HasForeignKey("TitleId");
                });
#pragma warning restore 612, 618
        }
    }
}
